name: Android CI

on:
  push:
    branches: [ "main" ]
    tags:
        "IntenAndroid"
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
    - uses: actions/checkout@v3
    - name: Setting JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
    - name: memberikan Perizinan gradlew
      run: chmod +x gradlew
    - name: Build debug Apk
      run: bash ./gradlew assembleDebug --stacktrace
    - name: Upload Ke dalam Artifact
      uses: actions/upload-artifact@v3.1.3
      with:
          name: Intent And Webview
          path: ./app/build/outputs/apk/debug/app-debug.apk
